### ISSUE TITLE
Custom Chat Problem

### ISSUE THREAD

**Issue by TempMF** [IcyStarFrost/Lambda-Players#105]
The Custom Chat addon (https://steamcommunity.com/sharedfiles/filedetails/?id=2799307109) does not seem to work properly with the Lambda Players. Anything they write is not shown on chat even tho what they write is shown in the console. The default chat is working fine but Custom Chat is not and I don't know if it's the Custom Chat addon's problem or the Lambda's.

**Comment by nikita488** [comment]
Also not working with this custom chat addon: https://steamcommunity.com/sharedfiles/filedetails/?id=1841694244

**Comment by IcyStarFrost** [comment]
It works perfectly fine for me

**Comment by IcyStarFrost** [comment]
I don't know what to tell you

**Comment by IcyStarFrost** [comment]
the hell the workshop version is broken

**Comment by TempMF** [comment]
Welp that's good.

**Comment by IcyStarFrost** [comment]
I found out the problem. The function responsible for posting chat messages was localized to save lookup times. However it seems the chat addons override the function which in return outdated the localized function. It's fixed now
