### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by Pop4484** [IcyStarFrost/Lambda-Players#106]
NextBot [5][npc_lambdaplayer] Error: lua/lambdaplayers/lambda/sv_locomotion.lua:52: bad argument #1 to 'SetMinLookAheadDistance' (number expected, got nil)

[Lambda Players | The Zeta Player Sequel] lua/entities/npc_lambdaplayer.lua:545: Tried to use a NULL physics object!
  1. SetPos - [C]:-1
   2. unknown - lua/entities/npc_lambdaplayer.lua:545 (x307)

i tried disabling all my addons, uninstalling all addons (unrelated, i needed disk space) and removed my legacy addons.

**Comment by Pop4484** [comment]
![kuva](https://user-images.githubusercontent.com/67192138/226160892-d43b51ea-453a-4bd8-871f-e15dd85cafa9.png)
in-game screenshot of a spawned lambda player

**Comment by IcyStarFrost** [comment]
Are you sure these are all the errors? Seems very unlikely that these are the only ones. It shouldnt be possible for the physics object code to error

**Comment by Pop4484** [comment]
ive seen some others too, but i havent gotten those now

**Comment by Pop4484** [comment]
got some more

[Lambda Players | The Zeta Player Sequel] lua/entities/npc_lambdaplayer.lua:192: attempt to get length of global 'Lambdaprofilepictures' (a nil value)
  1. unknown - lua/entities/npc_lambdaplayer.lua:192
   2. Spawn - [C]:-1
    3. InternalSpawnNPC - gamemodes/sandbox/gamemode/commands.lua:488
     4. Spawn_NPC - gamemodes/sandbox/gamemode/commands.lua:541
      5. unknown - gamemodes/sandbox/gamemode/commands.lua:573
       6. unknown - lua/includes/modules/concommand.lua:54


[Lambda Players | The Zeta Player Sequel] lua/lambdaplayers/lambda/sv_weaponhandling.lua:69: Tried to use a NULL entity!
  1. SetNoDraw - [C]:-1
   2. SwitchWeapon - lua/lambdaplayers/lambda/sv_weaponhandling.lua:69
    3. SwitchToSpawnWeapon - lua/lambdaplayers/lambda/sv_weaponhandling.lua:343
     4. OnSpawnedByPlayer - lua/lambdaplayers/lambda/sh_hooks.lua:520
      5. unknown - lua/lambdaplayers/autorun_includes/server/entityownership.lua:51

Timer Failed! [Simple][@lua/lambdaplayers/autorun_includes/server/entityownership.lua (line 47)]

[Lambda Players | The Zeta Player Sequel] lua/entities/npc_lambdaplayer.lua:545: Tried to use a NULL physics object!
  1. SetPos - [C]:-1
   2. unknown - lua/entities/npc_lambdaplayer.lua:545 (x2)

NextBot [5][npc_lambdaplayer] Error: lua/lambdaplayers/lambda/weapons/physicsgun.lua:262: Tried to use a NULL entity!

[Lambda Players | The Zeta Player Sequel] lua/entities/npc_lambdaplayer.lua:545: Tried to use a NULL physics object!
  1. SetPos - [C]:-1
   2. unknown - lua/entities/npc_lambdaplayer.lua:545 (x3)

**Comment by IcyStarFrost** [comment]
I can't do anything without every error you have gotten

**Comment by Pop4484** [comment]
im guessing thats all errors

**Comment by IcyStarFrost** [comment]
Your game is seriously messed up. I must ask this first. Is your Gmod pirated

**Comment by Pop4484** [comment]
nope, i bought it back in 2017

**Comment by Pop4484** [comment]
there's also this error

[Lambda Players | The Zeta Player Sequel] lua/entities/npc_lambdaplayer.lua:518: attempt to perform arithmetic on field 'l_WeaponSpeedMultiplier' (a nil value)
  1. unknown - lua/entities/npc_lambdaplayer.lua:518

that i get after shooting a lambda player (it respawns instantly)

**Comment by IcyStarFrost** [comment]
There is one glaring error. The Lambda profile pictures table is nil. This under no circumstances should be possible

**Comment by Pop4484** [comment]
oh, okay. no idea what's going on there. yesterday i tried modifying the code a little to fix the errors but i couldn't get it working myself.

**Comment by IcyStarFrost** [comment]
Is your lambdas from GitHub here or workshop?

**Comment by Pop4484** [comment]
workshop version

**Comment by Pop4484** [comment]
i tried downloading the github version too and i got the same errors

**Comment by Pop4484** [comment]
the weird part is that before the workshop release everything worked fine

**Comment by Pop4484** [comment]
(i no longer have the github version installed as of now)

**Comment by IcyStarFrost** [comment]
Last time I tested workshop version today everything worked fine. Try verifying your game and trying without any other addons again.

When you load in, first thing you should do is look in the problems menu and see if there are any errors. If not. Try spawning down lambdas

**Comment by Pop4484** [comment]
okay.

**Comment by Pop4484** [comment]
disabled every addon and legacy addon excluding lambda players, errors.

[Lambda Players | The Zeta Player Sequel] lua/lambdaplayers/autorun_includes/shared/filesystem.lua:171: attempt to get length of local 'content' (a nil value)
  1. GetPropTable - lua/lambdaplayers/autorun_includes/shared/filesystem.lua:171
   2. unknown - lua/autorun/lambdaplayers-autorun.lua:118


[Lambda Players | The Zeta Player Sequel] lua/weapons/gmod_tool/stools/lambdavoicelinetester.lua:59: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. func - lua/weapons/gmod_tool/stools/lambdavoicelinetester.lua:59
    3. FillViaFunction - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:134
     4. FillViaTable - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:126
      5. ActivateTool - lua/includes/modules/spawnmenu.lua:116
       6. Open - gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:130
        7. Run - gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:265
         8. unknown - gamemodes/base/gamemode/cl_spawnmenu.lua:11
          9. unknown - lua/includes/modules/concommand.lua:54


[Lambda Players | The Zeta Player Sequel] lua/entities/npc_lambdaplayer.lua:192: attempt to get length of global 'Lambdaprofilepictures' (a nil value)
  1. unknown - lua/entities/npc_lambdaplayer.lua:192
   2. Spawn - [C]:-1
    3. InternalSpawnNPC - gamemodes/sandbox/gamemode/commands.lua:488
     4. Spawn_NPC - gamemodes/sandbox/gamemode/commands.lua:541
      5. unknown - gamemodes/sandbox/gamemode/commands.lua:573
       6. unknown - lua/includes/modules/concommand.lua:54


[Lambda Players | The Zeta Player Sequel] lua/lambdaplayers/lambda/sv_weaponhandling.lua:69: Tried to use a NULL entity!
  1. SetNoDraw - [C]:-1
   2. SwitchWeapon - lua/lambdaplayers/lambda/sv_weaponhandling.lua:69
    3. SwitchToSpawnWeapon - lua/lambdaplayers/lambda/sv_weaponhandling.lua:343
     4. OnSpawnedByPlayer - lua/lambdaplayers/lambda/sh_hooks.lua:520
      5. unknown - lua/lambdaplayers/autorun_includes/server/entityownership.lua:51

Timer Failed! [Simple][@lua/lambdaplayers/autorun_includes/server/entityownership.lua (line 47)]
NextBot tickrate changed from 0 (0.000ms) to 1 (0.015ms)

[Lambda Players | The Zeta Player Sequel] lua/entities/npc_lambdaplayer.lua:545: Tried to use a NULL physics object!
  1. SetPos - [C]:-1
   2. unknown - lua/entities/npc_lambdaplayer.lua:545

NextBot [110][npc_lambdaplayer] Error: lua/lambdaplayers/lambda/sv_locomotion.lua:52: bad argument #1 to 'SetMinLookAheadDistance' (number expected, got nil)

[Lambda Players | The Zeta Player Sequel] lua/entities/npc_lambdaplayer.lua:545: Tried to use a NULL physics object!
  1. SetPos - [C]:-1
   2. unknown - lua/entities/npc_lambdaplayer.lua:545 (x64)

**Comment by IcyStarFrost** [comment]
Go to garrysmod/data and delete the lambda players folder and restart

**Comment by Pop4484** [comment]
that worked, thanks!
