### ISSUE TITLE
[Incompatibility] Names of Lambda players is always White in chat when using with BetterChat

### ISSUE THREAD

**Issue by nikita488** [IcyStarFrost/Lambda-Players#107]
The color of the Lambda player's name in the chat set in the settings is not taken into account when used together with [BetterChat](https://steamcommunity.com/sharedfiles/filedetails/?id=1841694244) addon. Works fine with ZetaPlayers.
![image](https://user-images.githubusercontent.com/6237881/226375778-7a0fb45b-640f-47e2-b8c8-dd7543794767.png)

**Comment by IcyStarFrost** [comment]
This is fixed now
