### ISSUE TITLE
conflicting with wiremod's hideChat E2 function

### ISSUE THREAD

**Issue by stingustooh** [IcyStarFrost/Lambda-Players#109]
issue's fairly inconsistent in which one (out of lambdaplayers chat messages or E2's hideChat) works, but i'm fairly certain they're fighting over the PlayerSay hook
seems that when lambdaplayers are broken, they just don't send messages in the chat
not getting any errors in the console about it

**Comment by IcyStarFrost** [comment]
Lambda Players do not return true or any value within their PlayerSay hooks so I doubt they have any issue there.  They do not use any hook for their text messages they simply send a net message to every player in the server that runs chat.AddText().

I don't get what you mean when they are broken they stop sending messages in chat. I need to know how they are broken

**Comment by IcyStarFrost** [comment]
Doing some testing, I'm not seeing any issue with hideChat() and Lambdas. hideChat() is properly hiding all my messages but every lambda is still able to chat. I just find it pretty odd a server side hook would presumably prevent a chat message made in the client realm. Have you tried with only the Lambdas and Wiremod as the only loaded addons?
