### ISSUE TITLE
Not Moving/Working At All

### ISSUE THREAD

**Issue by Davacado2** [IcyStarFrost/Lambda-Players#113]
![20230405133241_1](https://user-images.githubusercontent.com/129986697/230159189-dafb26a7-6ccc-41b3-8a6e-799ef7fddcfe.jpg)

not sure whats causing this, i have no other mods installed and im using the x64 version of Gmod, help grealty appreciated !!!

**Comment by CombineSlayer24** [comment]
If you posted the lua error, we could help you.

**Comment by CombineSlayer24** [comment]
If you posted the lua error, we could help you.
