### ISSUE TITLE
Missing feature on the building code of the Lambda Players, or maybe I'm missing a setting.

### ISSUE THREAD

**Issue by GustavRaispits** [IcyStarFrost/Lambda-Players#119]
The Lambda Players are way better compared to the Zeta Players, but I've noticed an issue that kills the experience of the Sandbox Gamemode.

I'm not speaking about the Dupe Building module that can be found through the workshop, but the built-in build feature on the main Lambda Players mod, I remember seeing the Zeta players picking the props using the Physgun for freezing and welding them onto other props, creating random structures without the need to activate the dupe building feature.

Settings used:

![G7qUE66](https://user-images.githubusercontent.com/34628862/236688785-4680ea15-00dd-4024-a736-f739cbd62f0b.png)
![KYvyb0W](https://user-images.githubusercontent.com/34628862/236688829-ec8f86d5-66f2-4147-a0bf-d5953296c62e.png)

I know it is on "Custom Random", but I've put the "Builder" behavior too as the default one for trying, beside the fact that this made the Lambda players randomly spawn props and carrying them around, there's no other result, I never see them building random structures without having to enable the Dupe Builder feature, which happened on the Zeta Players addon.

![E6fBbfY](https://user-images.githubusercontent.com/34628862/236689191-12dffa8d-f1e5-45ef-ab16-fb0286e60459.png)

Demo:

Check out the video: https://user-images.githubusercontent.com/34628862/236689047-37c258bd-a01d-431e-aff1-57221511b5fd.mp4

![ndiWDsj](https://user-images.githubusercontent.com/34628862/236689052-c1d7b0e4-4472-4be4-80c6-744bffd2e9b7.png)

That's more like the random props spawning feature that was present on the Zeta Players addon

I have every module installed beside the Dupe building feature.

Hoping to figure it out soon!

**Comment by IcyStarFrost** [comment]
As of the recent updates toward the side-main branch that will at some point be merged with main, spawning props and welding them to other props makes a return.
