### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by tiredsoot** [IcyStarFrost/Lambda-Players#70]
enabling x86-64: didn't work
reinstalling: didn't work
do i need to enable the zeta's for it to work?

**Comment by IcyStarFrost** [comment]
Are you *sure* you installed it correctly? Make sure you place the main folder in `garrysmod/addons/(lambdaplayersfolder)/(lua files, materials, ext)` If you pirated gmod then you are kinda screwed.

 If you can't install it, you should just wait until it is released to the steam workshop

**Comment by tiredsoot** [comment]
thanks, ill just wait
