### ISSUE TITLE
Seems like something related to the physicsgun.

### ISSUE THREAD

**Issue by Luke7381** [IcyStarFrost/Lambda-Players#76]
[lambda-players-master] addons/lambda-players-master/lua/lambdaplayers/lambda/weapons/physicsgun.lua:106: attempt to index global 'traceData' (a nil value)
  1. func - addons/lambda-players-master/lua/lambdaplayers/lambda/weapons/physicsgun.lua:106
   2. v - addons/lambda-players-master/lua/lambdaplayers/lambda/sh_util.lua:71
    3. unknown - lua/includes/modules/hook.lua:96

**Comment by IcyStarFrost** [comment]
Problem should be solved
